### ISSUE TITLE
As a user I want to read items from the table so that I can do something with them

### ISSUE THREAD

**Issue by flowersinthesand** [lecle/aloxide#19]
## Acceptance Criteria

- [ ] Define an interface e.g. ActiveRecord in RoR, EntityManager in JPA to interact with the persistence
- [ ] Determine fetch options to support
    - ICON doesn't store insertion orders
- [x] Implement a bridge for EOS
- [ ] Implement a bridge for ICON

**Comment by flowersinthesand** [comment]
>  Define an interface e.g. ActiveRecord in RoR, EntityManager in JPA to interact with the persistence

@manh-vv can you point the location of this interface?
