### ISSUE TITLE
As a user I want to allow the application users to store something in the table so that every node in the blockchain network can protect it from being tempered

### ISSUE THREAD

**Issue by flowersinthesand** [lecle/aloxide#21]
## Acceptance Criteria

- [x] Add a row creation feature to the above interface defined in https://github.com/lecle/aloxide/issues/19
- [x] Implement it for EOS
- [x] Implement it for ICON
