### ISSUE TITLE
As a user I want to run the api gateway standalone so that I can use and customize it for my dApp development

### ISSUE THREAD

**Issue by flowersinthesand** [lecle/aloxide#24]
## Acceptance Criteria

- [x] Determine a framework/library for building the API gateway
- [x] Allow to run in the standalone mode with given a dedicated port.
- [x] Make it compatible to work with existing an http/https server/library/module/framework/service like Node's http/https module, Express, AWS Lambda, etc.
- [x] Provide various configuration including tls/ssl, port, etc.
- [x] Make it scalable with ease.
