### ISSUE TITLE
As a user I want to configure a data store that the api gateway will use to manage data so that I can use my favorite one or existing one from other applications

### ISSUE THREAD

**Issue by flowersinthesand** [lecle/aloxide#25]
## Acceptance Criteria

- [ ] Determine an ORM solution like Sequelize.
    - It should support more than 4 data stores.
- [x] Read entity specifications and configure models for the determined ORM solution dynamically
- [x] Integrate the data access layer with the api gateway
- [ ] Allow to accept the configuration of existing ORM solution

**Comment by manh-vv** [comment]
I am going to make a refactoring on `@aloxide/demux` and `@aloxide/api-gateway` with the removal of `sequelize`.

- [ ] remove dependency of `sequelize` in `@aloxide/demux` and expose data access layer apis
- [ ] remove dependency of `sequelize` in `@aloxide/api-gateway` and expose data access layer apis

**Comment by flowersinthesand** [comment]
@manh-vv Then what package will use/depend Sequelize?

**Comment by manh-vv** [comment]
I think we don't need to use sequelize for the purpose of supporting a wide range of databases.

**Comment by manh-vv** [comment]
We can use any available ORM solution after #67 is merged.
