### ISSUE TITLE
As a user I want to mirror a smart contract table into a corresponding table of the data store in the api gateway so that I can call sophisticated queries to the table in the api gateway

### ISSUE THREAD

**Issue by flowersinthesand** [lecle/aloxide#26]
## Acceptance Criteria

- [x] Sync up smart contracts using Demux given entities
- [x] Write a Demux integration for ICON
- [x] Feed mirror tables with smart contract logs/states from Demux
- [x] Generate a GraphQL API from entity and mirror table
- [x] Make the resulting GraphQL API configure
